services:
  # ------------------------------------
  # 1. MongoDB Database
  # ------------------------------------
  mongodb:
    image: mongo:6.0
    container_name: adad-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      PORT: 27017
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    networks:
      - adad_network

  # ------------------------------------
  # 2. Node.js Backend / Express Server
  # ------------------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: adad-backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://user:password@mongodb:27017/adad_db?authSource=admin
    env_file:
      - ./.env
    expose:
      - 5000
    networks:
      - adad_network
    depends_on:
      - mongodb

  # ------------------------------------
  # 3. React Frontend Client
  # ------------------------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: adad-frontend
    command: npm run start
    volumes:
      # Map local code to the container for live-reloading
      - ./frontend:/app
      # Prevents node_modules from being overwritten by the volume mount
      - /app/node_modules
    expose:
      - 3000
    networks:
      - adad_network
    depends_on:
      - backend

  # ------------------------------------
  # 4. NGINX Reverse Proxy
  # ------------------------------------
  nginx:
    image: nginx:stable-alpine
    container_name: adad-nginx-proxy
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - adad_network
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:

networks:
  adad_network:
    driver: bridge

