services:
  # ------------------------------------
  # 1. MongoDB Database
  # ------------------------------------
  mongodb:
    image: mongo:6.0
    container_name: adad-mongodb
    restart: always
    environment:
      # Use a secure password in production!
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      # Persistent storage for your database data
      - mongo_data:/data/db
    environment:
      PORT: 27017
    expose:
      - 27017
    networks:
      - adad_network

  # ------------------------------------
  # 2. Node.js Backend / Express Server
  # ------------------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: adad-backend
    restart: always
    # Map your local code to the container for hot-reloading
    volumes:
      - ./backend:/app
      # Prevents node_modules from being overwritten by the volume mount
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://user:password@mongodb:27017/adad_db?authSource=admin
    # The backend is exposed internally to NGINX on port 5000
    expose:
      - 5000
    networks:
      - adad_network
    depends_on:
      - mongodb

  # ------------------------------------
  # 3. React Frontend Client
  # ------------------------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: adad-frontend
    # Assuming your React app is set up to use create-react-app or similar
    # which usually runs on port 3000.
    command: npm run start
    volumes:
      # Map your local code to the container for live-reloading
      - ./frontend:/app
      # Prevents node_modules from being overwritten by the volume mount
      - /app/node_modules
    expose:
      - 3000
    networks:
      - adad_network
    depends_on:
      - backend

  # ------------------------------------
  # 4. NGINX Reverse Proxy
  # ------------------------------------
  nginx:
    image: nginx:stable-alpine
    container_name: adad-nginx-proxy
    restart: always
    volumes:
      # Mount the custom NGINX configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # Expose the application to the host machine on port 8080
    ports:
      - "8080:80"
    networks:
      - adad_network
    depends_on:
      - frontend
      - backend

# Define persistent volume for MongoDB
volumes:
  mongo_data:

# Define a custom network for all services
networks:
  adad_network:
    driver: bridge

